Repository AY2021S1-CS2103T-W16-1/tp, pull requests merged in 2020-10, with the labels that each got.

#50 Koh Zhe Hao - Mid v1.2
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Company.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/role/CompanyRole.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompanyRole.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/role/RoleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#61 Update Model for Meeting and List Meeting
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: enhancement

#62 Add Meeting UI and Find Meeting Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindMeetingCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/DataContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meeting/TitleContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/MeetingListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingListCard.fxml
  src/main/resources/view/MeetingListPanel.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
  src/test/java/seedu/address/logic/parser/FindMeetingCommandParserTest.java
  src/test/java/seedu/address/model/meeting/DataContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: enhancement, priority.High

#63 Add Delete Meeting Command
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteMeetingCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteMeetingCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: documentation, enhancement

#64 Add meeting command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/AddParticipantCommand.java
  src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/AddParticipantCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/meeting/DateTime.java
  src/main/java/seedu/address/model/meeting/Duration.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/meeting/DateTimeTest.java
Labels: documentation, enhancement

#65 Add feature: edit meeting command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/Duration.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditMeetingCommandTest.java
  src/test/java/seedu/address/testutil/EditMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: documentation, enhancement

#66 Update docs for add_part
  docs/UserGuide.md
Labels: documentation

#80 Update DG
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/AddMeetingSequenceDiagram.puml
  docs/diagrams/EditMeetingSequenceDiagram.puml
  docs/images/AddMeetingSequenceDiagram.png
  docs/images/EditMeetingSequenceDiagram.png
Labels: documentation

#85 Update developer guide
  docs/DeveloperGuide.html
  docs/DeveloperGuide.md
  docs/diagrams/FindMeetingClassDiagram.puml
  docs/diagrams/FindMeetingSequenceDiagram.puml
  docs/images/FindMeetingClassDiagram.png
  docs/images/FindMeetingSequenceDiagram.png
Labels: documentation

#89 Update DG with Company and CompanyRole
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#92 UI Overhaul
  src/main/java/seedu/address/model/meeting/DateTime.java
  src/main/java/seedu/address/model/meeting/Duration.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/MeetingListPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/fonts/Inter-Bold.ttf
  src/main/resources/fonts/Inter-Light.ttf
  src/main/resources/fonts/Inter-Regular.ttf
  src/main/resources/images/default_profile.png
  src/main/resources/images/email.png
  src/main/resources/images/home.png
  src/main/resources/images/location.png
  src/main/resources/images/phone.png
  src/main/resources/images/with.png
  src/main/resources/images/work.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingListCard.fxml
  src/main/resources/view/MeetingListPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/model/meeting/DateTimeTest.java
Labels: enhancement

#94 Facilitate Recurring Meetings
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/meeting/DateTime.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/Recurrence.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/model/meeting/DateTimeTest.java
  src/test/java/seedu/address/model/meeting/RecurrenceTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/RecurringMeeting.java
Labels: enhancement

#95 Update Delete for Recurrences
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/parser/DeleteMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
Labels: bug, enhancement, help wanted

#99 Implement edit user preference
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditUserPrefCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditUserPrefCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: priority.High

#103 Undo Command
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/CommandSession.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/DateTime.java
  src/main/java/seedu/address/model/meeting/Duration.java
  src/main/java/seedu/address/model/meeting/Location.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/Recurrence.java
  src/main/java/seedu/address/model/meeting/Title.java
  src/main/java/seedu/address/model/memento/History.java
  src/main/java/seedu/address/model/memento/RecretaryState.java
  src/main/java/seedu/address/model/memento/StateManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Company.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/CommandSessionTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearContactCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteContactCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteParticipantCommandTest.java
  src/test/java/seedu/address/logic/commands/EditContactCommandTest.java
  src/test/java/seedu/address/logic/commands/EditMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/FindContactCommandTest.java
  src/test/java/seedu/address/logic/commands/FindMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
  src/test/java/seedu/address/logic/commands/RemindMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandIntegrationTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/memento/HistoryTest.java
Labels: enhancement, priority.High

#101 CLI Update
  src/main/java/seedu/address/logic/CommandSession.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/memento/History.java
  src/main/java/seedu/address/model/memento/RecretaryState.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/CommandSessionTest.java
Labels: enhancement, priority.Medium

#97 Add attribute
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/meeting/DateTime.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonMap.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/MeetingListPanel.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UndoCommandIntegrationTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/meeting/DateTimeTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
  src/test/java/seedu/address/model/meeting/UniqueMeetingListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug, priority.High

#104 v1.3b meetings conflict detection
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/EditMeetingCommandTest.java
Labels: bug, enhancement, priority.High

#113 Fix bug for delete contact
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/person/UniquePersonMap.java
Labels: bug

#115 Implement System timer
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindMeetingClassDiagram.puml
  docs/diagrams/MeetingClassDiag.puml
  docs/diagrams/SchedulerClassDiagram.puml
  docs/images/FindMeetingClassDiagram.png
  docs/images/MeetingClassDiag.png
  docs/images/SchedulerClassDiagram.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/RemindMeetingCommand.java
  src/main/java/seedu/address/logic/scheduler/RefreshTask.java
  src/main/java/seedu/address/logic/scheduler/ScheduledTask.java
  src/main/java/seedu/address/logic/scheduler/Scheduler.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
Labels: documentation, enhancement, priority.High

#116 Update algorithm for conflict checking
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/MeetingWithinDaysPredicate.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
Labels: enhancement, priority.High

#169 Popup Notifications (beta version for demo, untested)
  build.gradle
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/scheduler/RefreshTask.java
  src/main/java/seedu/address/logic/scheduler/ReminderPopupTask.java
  src/main/java/seedu/address/logic/scheduler/ScheduledTask.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReminderPopup.java
  src/main/resources/sounds/notification.mp3
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReminderPopup.fxml
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
Labels: enhancement
