Repository AY2021S1-CS2103T-W16-1/tp, pull requests merged in 2020-11, with the labels that each got.

#171 v1.4 minor adjustment according to feedback from PE-Dry run
  docs/UserGuide.md
  docs/images/remind_meeting_after.png
  docs/images/remind_meeting_before.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/AddParticipantCommand.java
  src/main/java/seedu/address/logic/commands/ClearContactCommand.java
  src/main/java/seedu/address/logic/commands/ClearMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteParticipantCommand.java
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/EditUserPrefCommand.java
  src/main/java/seedu/address/logic/commands/ExportMeetingCommand.java
  src/main/java/seedu/address/logic/commands/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/FindMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ImportMeetingCommand.java
  src/main/java/seedu/address/logic/commands/ListContactCommand.java
  src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
  src/main/java/seedu/address/logic/commands/RemindMeetingCommand.java
  src/main/java/seedu/address/logic/parser/EditUserPrefCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemindMeetingCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/meeting/MeetingWithinHoursPredicate.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/model/person/Company.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/role/CompanyRole.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/RemindMeetingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemindMeetingCommandParserTest.java
  src/test/java/seedu/address/model/meeting/MeetingWithinHoursPredicateTest.java
Labels: documentation, priority.High

#174 Branch v1.4 bug fix
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/scheduler/ReminderPopupTask.java
  src/main/java/seedu/address/logic/scheduler/Scheduler.java
  src/main/java/seedu/address/model/meeting/Duration.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/Recurrence.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/meeting/DurationTest.java
  src/test/java/seedu/address/model/meeting/MeetingTest.java
Labels: documentation, enhancement

#177 V.14 amendment
  docs/AboutUs.md
  docs/team/tan-xuan-zhi.md
  docs/team/xxzz-tt.md
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/AddParticipantCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddParticipantCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/DateTime.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/test/java/seedu/address/model/meeting/DateTimeTest.java
Labels: bug

#180 Update PPP
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/koh-zhe-hao.md
  docs/team/zhaohuanqdcn.md
Labels: documentation

#182 Reformat UG (partially) and update PPP
  docs/UserGuide.md
  docs/images/addfirstParticipant.png
  docs/team/xxzz-tt.md
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/Recurrence.java
Labels: bug, documentation

#183 Update user guide
  docs/UserGuide.md
  docs/images/addFirstParticipant.png
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteParticipantCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/Recurrence.java
  src/main/java/seedu/address/storage/JsonAdaptedMeeting.java
  src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
  src/test/java/seedu/address/logic/commands/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteParticipantCommandTest.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: documentation

#185 Update documentation
  docs/UserGuide.md
Labels: documentation

#187 v1.4 doc update
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/zhaohuanqdcn.md
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditMeetingCommandParserTest.java
Labels: documentation

#192 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddContactActivityDiagram.puml
  docs/diagrams/AddContactSequenceDiagram.puml
  docs/diagrams/AddMeetingActivityDiagram.puml
  docs/diagrams/AddMeetingSequenceDiagram.puml
  docs/diagrams/EditContactActivityDiagram.puml
  docs/diagrams/EditContactSequenceDiagram.puml
  docs/diagrams/EditMeetingActivityDiagram.puml
  docs/diagrams/EditMeetingSequenceDiagram.puml
  docs/images/AddContactActivityDiagram.png
  docs/images/AddContactSequenceDiagram.png
  docs/images/AddMeetingActivityDiagram.png
  docs/images/AddMeetingSequenceDiagram.png
  docs/images/EditContactActivityDiagram.png
  docs/images/EditContactSequenceDiagram.png
  docs/images/EditMeetingActivityDiagram.png
  docs/images/EditMeetingSequenceDiagram.png
Labels: documentation

#194 v1.4 documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/edituserpref.png
  docs/team/koh-zhe-hao.md
Labels: documentation

#198 Update Docs
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteContactSequenceDiagram.puml
  docs/diagrams/SchedulerClassDiagram.puml
  docs/images/DeleteContactSequenceDiagram.png
  docs/images/PopUpReminder.jpg
  docs/images/SchedulerClassDiagram.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#199 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/EditUserPrefClassDiagram.puml
  docs/diagrams/EditUserPrefSequenceDiagram.puml
  docs/diagrams/RemindMeetingClassDiagram.puml
  docs/diagrams/RemindMeetingSequenceDiagram.puml
  docs/images/EditUserPrefClassDiagram.png
  docs/images/EditUserPrefSequenceDiagram.png
  docs/images/RemindMeetingClassDiagram.png
  docs/images/RemindMeetingSequenceDiagram.png
  docs/team/koh-zhe-hao.md
Labels: documentation

#200 Update PPP
  docs/UserGuide.md
  docs/team/xxzz-tt.md
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#202 Update PPP
  docs/team/zhaohuanqdcn.md
Labels: documentation

#204 Update PPP
  docs/team/zhaohuanqdcn.md
Labels: documentation

#209 Update user guide for CS2101
  docs/UserGuide.md
  docs/images/addAfter.png
  docs/images/addBefore.png
  docs/images/contacts.png
Labels: documentation

#212 2102UG Update
  docs/UserGuide.md
Labels: documentation
